// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATDKZjhnIsyISMXoL9NkJMb0AZ1-swPOQ',
    appId: '1:150545923360:web:1b1ff40a441e7d20246b45',
    messagingSenderId: '150545923360',
    projectId: 'prm393-6e0da',
    authDomain: 'prm393-6e0da.firebaseapp.com',
    databaseURL: 'https://prm393-6e0da-default-rtdb.firebaseio.com',
    storageBucket: 'prm393-6e0da.firebasestorage.app',
    measurementId: 'G-WCN5HWXDXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuxCVsBqUVC9i-b7T77mC6k28c9czNKBg',
    appId: '1:150545923360:android:e30e23431734ea58246b45',
    messagingSenderId: '150545923360',
    projectId: 'prm393-6e0da',
    databaseURL: 'https://prm393-6e0da-default-rtdb.firebaseio.com',
    storageBucket: 'prm393-6e0da.firebasestorage.app',
  );
}
