name: movieapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.2.1
  dio: ^5.4.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^4.0.0
  path_provider: ^2.1.2
  cached_network_image: ^3.3.1
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  video_player: ^2.8.2
  chewie: ^1.8.5
  android_pip: ^2.0.2
  wakelock_plus: ^1.2.5
  ffmpeg_kit_flutter_new_https: ^2.1.0
  permission_handler: ^11.3.0
  connectivity_plus: ^6.0.5

  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  firebase_database: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png